export const mockIds = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

export const mockData = {
  1: {
    id: 1,
    title: 'Product 1',
    link: 'https://',
    created_at: '2020/4/6',
    description: 'Huawei is a leading global provider of information and communications technology (ICT) infrastructure and smart devices.',
    ingredient: 'peptide',
    category_skinCare: 'Sun Protection',
    category_application: 'topical',
    category_product: 'Face oil',
  },
  2: {
    id: 2,
    title: 'Product 2',
    link: 'https://',
    created_at: '2020/4/6',
    description: 'iPod touch now comes with the A10 Fusion chip, which powers augmented reality games and apps.',
    ingredient: 'peptide',
    category_skinCare: 'Sun Protection',
    category_application: 'topical',
    category_product: 'Face oil',
  },
  3: {
    id: 3,
    title: 'Product 3',
    link: 'https://',
    created_at: '2020/4/6',
    description: 'Vodafone Group plc /ˈvoʊdəfoʊn/ is a British multinational telecommunications company.',
    ingredient: 'peptide',
    category_skinCare: 'Sun Protection',
    category_application: 'topical',
    category_product: 'Face oil',
  },
  4: {
    id: 4,
    title: 'Product 4',
    link: 'https://',
    created_at: '2020/4/6',
    description: 'Microsoft Corporation is an American multinational technology company with headquarters in Redmond, Washington.',
    ingredient: 'peptide',
    category_skinCare: 'Sun Protection',
    category_application: 'topical',
    category_product: 'Face oil',
  },
  5: {
    id: 5,
    title: 'Product 5',
    link: 'https://',
    created_at: '2020/4/6',
    description: 'Sony at InfoComm 2020. InfoComm is going online for 2020 with a virtual audiovisual and interactive experience.',
    ingredient: 'peptide',
    category_skinCare: 'Sun Protection',
    category_application: 'topical',
    category_product: 'Face oil',
  },
  6: {
    id: 6,
    title: 'Product 6',
    link: 'https://',
    created_at: '2020/4/6',
    description: 'Nokia is an innovative global leader in 5G, networks and phones. See how we create the technology to connect the world.',
    ingredient: 'peptide',
    category_skinCare: 'Sun Protection',
    category_application: 'topical',
    category_product: 'Face oil',
  },
  7: {
    id: 7,
    title: 'Product 7',
    link: 'https://',
    created_at: '2020/4/6',
    description: 'BlackBerry provides enterprises and governments with the software and services they need to secure the Internet of Things.',
    ingredient: 'peptide',
    category_skinCare: 'Sun Protection',
    category_application: 'topical',
    category_product: 'Face oil',
  },
  8: {
    id: 8,
    title: 'Product 8',
    link: 'https://',
    created_at: '2020/4/6',
    description: 'Samsung helps you discover a wide range of home electronics with cutting-edge technology including smartphones, tablets, TVs, home appliances and more.',
    ingredient: 'peptide',
    category_skinCare: 'Sun Protection',
    category_application: 'topical',
    category_product: 'Face oil',
  },
  9: {
    id: 9,
    title: 'Product 9',
    link: 'https://',
    created_at: '2020/4/6',
    description: 'Toshiba Corporation is a Japanese multinational conglomerate headquartered in Minato, Tokyo.',
    ingredient: 'peptide',
    category_skinCare: 'Sun Protection',
    category_application: 'topical',
    category_product: 'Face oil',
  },
  10: {
    id: 10,
    title: 'Product 10',
    link: 'https://',
    created_at: '2020/4/6',
    description: 'Hitachi delivers digital solutions utilizing Lumada in five sectors including Mobility, Smart Life, Industry, Energy and IT, to increase our customer.',
    ingredient: 'peptide',
    category_skinCare: 'Sun Protection',
    category_application: 'topical',
    category_product: 'Face oil',
  },
}