export const mockData = {
  1: {
    id: 1,
    name: 'Huawei',
    price: '$190',
    created_at: '2020/4/6',
    description: 'Huawei is a leading global provider of information and communications technology (ICT) infrastructure and smart devices.',
  },
  2: {
    id: 2,
    name: 'iPod touch',
    price: '$190',
    created_at: '2020/4/6',
    description: 'iPod touch now comes with the A10 Fusion chip, which powers augmented reality games and apps.',
  },
  3: {
    id: 3,
    name: 'Vodafone',
    price: '$190',
    created_at: '2020/4/6',
    description: 'Vodafone Group plc /ˈvoʊdəfoʊn/ is a British multinational telecommunications company.',
  },
  4: {
    id: 4,
    name: 'Microsoft',
    price: '$190',
    created_at: '2020/4/6',
    description: 'Microsoft Corporation is an American multinational technology company with headquarters in Redmond, Washington.',
  },
  5: {
    id: 5,
    name: 'Sony',
    price: '$190',
    created_at: '2020/4/6',
    description: 'Sony at InfoComm 2020. InfoComm is going online for 2020 with a virtual audiovisual and interactive experience.',
  },
  6: {
    id: 6,
    name: 'Nokia',
    price: '$190',
    created_at: '2020/4/6',
    description: 'Nokia is an innovative global leader in 5G, networks and phones. See how we create the technology to connect the world.',
  },
  7: {
    id: 7,
    name: 'Blackberry',
    price: '$190',
    created_at: '2020/4/6',
    description: 'BlackBerry provides enterprises and governments with the software and services they need to secure the Internet of Things.',
  },
  8: {
    id: 8,
    name: 'Samsung',
    price: '$190',
    created_at: '2020/4/6',
    description: 'Samsung helps you discover a wide range of home electronics with cutting-edge technology including smartphones, tablets, TVs, home appliances and more.',
  },
  9: {
    id: 9,
    name: 'Toshiba',
    price: '$190',
    created_at: '2020/4/6',
    description: 'Toshiba Corporation is a Japanese multinational conglomerate headquartered in Minato, Tokyo.',
  },
  10: {
    id: 10,
    name: 'Hitachi',
    price: '$190',
    created_at: '2020/4/6',
    description: 'Hitachi delivers digital solutions utilizing Lumada in five sectors including Mobility, Smart Life, Industry, Energy and IT, to increase our customer',
  },
}